# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :"Lesson9" => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--cpus", "4"] 
            vb.customize ["modifyvm", :id, "--memory", "4096"]
          end
          
          box.vm.provision :shell, :inline => "setenforce 0", run: "always"
          box.vm.provision "file", source: "/home/mity/Documents/OTUS_Linux_Prof/Lesson9/script/", destination: "/tmp/"
          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
                        yum install epel-release -y
                        yum install spawn-fcgi php php-cli mod_fcgid httpd -y
                        cp /tmp/script/alert_add.sh /opt
			cp /tmp/script/tail_add.sh /opt
			cp /tmp/script/watchlog /etc/sysconfig
			sudo cp /tmp/script/watchlog.service /etc/systemd/system
			sudo cp -f /tmp/script/spawn-fcgi /etc/sysconfig/
			sudo cp /tmp/script/spawn-fcgi.service /etc/systemd/system
                        sudo cp /tmp/script/first.conf /etc/httpd/conf
			sudo cp /tmp/script/httpd-first /etc/sysconfig
                        sudo cp /tmp/script/httpd-second /etc/sysconfig
                        sudo cp '/tmp/script/httpd@first.service' /etc/systemd/system
			sudo cp '/tmp/script/httpd@second.service' /etc/systemd/system
                        sudo cp /tmp/script/first.conf /etc/httpd/conf
                        sudo cp /tmp/script/second.conf /etc/httpd/conf
			cp /tmp/script/watchlog.sh /opt
			sudo cp /tmp/script/watchlog.timer /etc/systemd/system
                        chmod +x /opt/*.sh
                        (sudo crontab -l | 2>/dev/null; echo "*/3 * * * * /opt/tail_add.sh"; echo "*/5 * * * * /opt/alert_add.sh") | crontab -
                        sudo systemctl start watchlog.timer
			sudo systemctl start watchlog.service
			sudo systemctl enable watchlog.timer
                        sudo systemctl start spawn-fcgi
                        sudo systemctl daemon-reload
			sudo systemctl start httpd@first
			sudo systemctl start httpd@second


          SHELL

      end
  end
end
